ReversiPython: reversi.model.ReversiAnz.ReversiAnz Class Reference
reversi.model.ReversiAnz.ReversiAnz Class Reference
リバーシ解析クラス
Public Member Functions
def __init__ (self)
コンストラクタ
def getMin (self)
ゲッター
def setMin (self, min)
セッター
def getMax (self)
ゲッター
def setMax (self, max)
セッター
def getAvg (self)
ゲッター
def setAvg (self, avg)
セッター
def getPointCnt (self)
ゲッター
def setPointCnt (self, pointCnt)
セッター
def getEdgeCnt (self)
ゲッター
def setEdgeCnt (self, edgeCnt)
セッター
def getEdgeSideOneCnt (self)
ゲッター
def setEdgeSideOneCnt (self, edgeSideOneCnt)
セッター
def getEdgeSideTwoCnt (self)
ゲッター
def setEdgeSideTwoCnt (self, edgeSideTwoCnt)
セッター
def getEdgeSideThreeCnt (self)
ゲッター
def setEdgeSideThreeCnt (self, edgeSideThreeCnt)
セッター
def getEdgeSideOtherCnt (self)
ゲッター
def setEdgeSideOtherCnt (self, edgeSideOtherCnt)
セッター
def getOwnMin (self)
ゲッター
def setOwnMin (self, ownMin)
セッター
def getOwnMax (self)
ゲッター
def setOwnMax (self, ownMax)
セッター
def getOwnAvg (self)
ゲッター
def setOwnAvg (self, ownAvg)
セッター
def getOwnPointCnt (self)
ゲッター
def setOwnPointCnt (self, ownPointCnt)
セッター
def getOwnEdgeCnt (self)
ゲッター
def setOwnEdgeCnt (self, ownEdgeCnt)
セッター
def getOwnEdgeSideOneCnt (self)
ゲッター
def setOwnEdgeSideOneCnt (self, ownEdgeSideOneCnt)
セッター
def getOwnEdgeSideTwoCnt (self)
ゲッター
def setOwnEdgeSideTwoCnt (self, ownEdgeSideTwoCnt)
セッター
def getOwnEdgeSideThreeCnt (self)
ゲッター
def setOwnEdgeSideThreeCnt (self, ownEdgeSideThreeCnt)
セッター
def getOwnEdgeSideOtherCnt (self)
ゲッター
def setOwnEdgeSideOtherCnt (self, ownEdgeSideOtherCnt)
セッター
def getBadPoint (self)
ゲッター
def setBadPoint (self, badPoint)
セッター
def getGoodPoint (self)
ゲッター
def setGoodPoint (self, goodPoint)
セッター
def reset (self)
リセット
Properties
min = property(getMin, setMin)
max = property(getMax, setMax)
avg = property(getAvg, setAvg)
pointCnt = property(getPointCnt, setPointCnt)
edgeCnt = property(getEdgeCnt, setEdgeCnt)
edgeSideOneCnt = property(getEdgeSideOneCnt, setEdgeSideOneCnt)
edgeSideTwoCnt = property(getEdgeSideTwoCnt, setEdgeSideTwoCnt)
edgeSideThreeCnt = property(getEdgeSideThreeCnt, setEdgeSideThreeCnt)
edgeSideOtherCnt = property(getEdgeSideOtherCnt, setEdgeSideOtherCnt)
ownMin = property(getOwnMin, setOwnMin)
ownMax = property(getOwnMax, setOwnMax)
ownAvg = property(getOwnAvg, setOwnAvg)
ownPointCnt = property(getOwnPointCnt, setOwnPointCnt)
ownEdgeCnt = property(getOwnEdgeCnt, setOwnEdgeCnt)
ownEdgeSideOneCnt = property(getOwnEdgeSideOneCnt, setOwnEdgeSideOneCnt)
ownEdgeSideTwoCnt = property(getOwnEdgeSideTwoCnt, setOwnEdgeSideTwoCnt)
ownEdgeSideThreeCnt = property(getOwnEdgeSideThreeCnt, setOwnEdgeSideThreeCnt)
ownEdgeSideOtherCnt = property(getOwnEdgeSideOtherCnt, setOwnEdgeSideOtherCnt)
badPoint = property(getBadPoint, setBadPoint)
goodPoint = property(getGoodPoint, setGoodPoint)
Private Attributes
__min
__max
__avg
__pointCnt
__edgeCnt
__edgeSideOneCnt
__edgeSideTwoCnt
__edgeSideThreeCnt
__edgeSideOtherCnt
__ownMin
__ownMax
__ownAvg
__ownPointCnt
__ownEdgeCnt
__ownEdgeSideOneCnt
__ownEdgeSideTwoCnt
__ownEdgeSideThreeCnt
__ownEdgeSideOtherCnt
__badPoint
__goodPoint
Detailed Description
リバーシ解析クラス
Definition at line 25 of file ReversiAnz.py.
Constructor & Destructor Documentation
__init__()
def reversi.model.ReversiAnz.ReversiAnz.__init__ (self)
コンストラクタ
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 36 of file ReversiAnz.py.
Member Function Documentation
getAvg()
def reversi.model.ReversiAnz.ReversiAnz.getAvg (self)
ゲッター
Parameters
[in] self
Returns
avg
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 98 of file ReversiAnz.py.
getBadPoint()
def reversi.model.ReversiAnz.ReversiAnz.getBadPoint (self)
ゲッター
Parameters
[in] self
Returns
badPoint
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 498 of file ReversiAnz.py.
getEdgeCnt()
def reversi.model.ReversiAnz.ReversiAnz.getEdgeCnt (self)
ゲッター
Parameters
[in] self
Returns
edgeCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 148 of file ReversiAnz.py.
getEdgeSideOneCnt()
def reversi.model.ReversiAnz.ReversiAnz.getEdgeSideOneCnt (self)
ゲッター
Parameters
[in] self
Returns
edgeSideOneCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 173 of file ReversiAnz.py.
getEdgeSideOtherCnt()
def reversi.model.ReversiAnz.ReversiAnz.getEdgeSideOtherCnt (self)
ゲッター
Parameters
[in] self
Returns
edgeSideOtherCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 248 of file ReversiAnz.py.
getEdgeSideThreeCnt()
def reversi.model.ReversiAnz.ReversiAnz.getEdgeSideThreeCnt (self)
ゲッター
Parameters
[in] self
Returns
edgeSideThreeCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 223 of file ReversiAnz.py.
getEdgeSideTwoCnt()
def reversi.model.ReversiAnz.ReversiAnz.getEdgeSideTwoCnt (self)
ゲッター
Parameters
[in] self
Returns
edgeSideTwoCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 198 of file ReversiAnz.py.
getGoodPoint()
def reversi.model.ReversiAnz.ReversiAnz.getGoodPoint (self)
ゲッター
Parameters
[in] self
Returns
goodPoint
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 523 of file ReversiAnz.py.
getMax()
def reversi.model.ReversiAnz.ReversiAnz.getMax (self)
ゲッター
Parameters
[in] self
Returns
max
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 73 of file ReversiAnz.py.
getMin()
def reversi.model.ReversiAnz.ReversiAnz.getMin (self)
ゲッター
Parameters
[in] self
Returns
min
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 48 of file ReversiAnz.py.
getOwnAvg()
def reversi.model.ReversiAnz.ReversiAnz.getOwnAvg (self)
ゲッター
Parameters
[in] self
Returns
ownAvg
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 323 of file ReversiAnz.py.
getOwnEdgeCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnEdgeCnt (self)
ゲッター
Parameters
[in] self
Returns
ownEdgeCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 373 of file ReversiAnz.py.
getOwnEdgeSideOneCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnEdgeSideOneCnt (self)
ゲッター
Parameters
[in] self
Returns
ownEdgeSideOneCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 398 of file ReversiAnz.py.
getOwnEdgeSideOtherCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnEdgeSideOtherCnt (self)
ゲッター
Parameters
[in] self
Returns
ownEdgeSideOtherCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 473 of file ReversiAnz.py.
getOwnEdgeSideThreeCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnEdgeSideThreeCnt (self)
ゲッター
Parameters
[in] self
Returns
ownEdgeSideThreeCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 448 of file ReversiAnz.py.
getOwnEdgeSideTwoCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnEdgeSideTwoCnt (self)
ゲッター
Parameters
[in] self
Returns
ownEdgeSideTwoCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 423 of file ReversiAnz.py.
getOwnMax()
def reversi.model.ReversiAnz.ReversiAnz.getOwnMax (self)
ゲッター
Parameters
[in] self
Returns
ownMax
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 298 of file ReversiAnz.py.
getOwnMin()
def reversi.model.ReversiAnz.ReversiAnz.getOwnMin (self)
ゲッター
Parameters
[in] self
Returns
ownMin
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 273 of file ReversiAnz.py.
getOwnPointCnt()
def reversi.model.ReversiAnz.ReversiAnz.getOwnPointCnt (self)
ゲッター
Parameters
[in] self
Returns
ownPointCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 348 of file ReversiAnz.py.
getPointCnt()
def reversi.model.ReversiAnz.ReversiAnz.getPointCnt (self)
ゲッター
Parameters
[in] self
Returns
pointCnt
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 123 of file ReversiAnz.py.
reset()
def reversi.model.ReversiAnz.ReversiAnz.reset (self)
リセット
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 548 of file ReversiAnz.py.
Referenced by reversi.model.ReversiAnz.ReversiAnz.__init__(), reversi.model.ReversiHistory.ReversiHistory.__init__(), and reversi.model.ReversiSetting.ReversiSetting.__init__().
setAvg()
def reversi.model.ReversiAnz.ReversiAnz.setAvg (self, avg)
セッター
Parameters
[in] self
[in] avg
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 111 of file ReversiAnz.py.
setBadPoint()
def reversi.model.ReversiAnz.ReversiAnz.setBadPoint (self, badPoint)
セッター
Parameters
[in] self
[in] badPoint
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 511 of file ReversiAnz.py.
setEdgeCnt()
def reversi.model.ReversiAnz.ReversiAnz.setEdgeCnt (self, edgeCnt)
セッター
Parameters
[in] self
[in] edgeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 161 of file ReversiAnz.py.
setEdgeSideOneCnt()
def reversi.model.ReversiAnz.ReversiAnz.setEdgeSideOneCnt (self, edgeSideOneCnt)
セッター
Parameters
[in] self
[in] edgeSideOneCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 186 of file ReversiAnz.py.
setEdgeSideOtherCnt()
def reversi.model.ReversiAnz.ReversiAnz.setEdgeSideOtherCnt (self, edgeSideOtherCnt)
セッター
Parameters
[in] self
[in] edgeSideOtherCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 261 of file ReversiAnz.py.
setEdgeSideThreeCnt()
def reversi.model.ReversiAnz.ReversiAnz.setEdgeSideThreeCnt (self, edgeSideThreeCnt)
セッター
Parameters
[in] self
[in] edgeSideThreeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 236 of file ReversiAnz.py.
setEdgeSideTwoCnt()
def reversi.model.ReversiAnz.ReversiAnz.setEdgeSideTwoCnt (self, edgeSideTwoCnt)
セッター
Parameters
[in] self
[in] edgeSideTwoCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 211 of file ReversiAnz.py.
setGoodPoint()
def reversi.model.ReversiAnz.ReversiAnz.setGoodPoint (self, goodPoint)
セッター
Parameters
[in] self
[in] goodPoint
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 536 of file ReversiAnz.py.
setMax()
def reversi.model.ReversiAnz.ReversiAnz.setMax (self, max)
セッター
Parameters
[in] self
[in] max
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 86 of file ReversiAnz.py.
setMin()
def reversi.model.ReversiAnz.ReversiAnz.setMin (self, min)
セッター
Parameters
[in] self
[in] min
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 61 of file ReversiAnz.py.
setOwnAvg()
def reversi.model.ReversiAnz.ReversiAnz.setOwnAvg (self, ownAvg)
セッター
Parameters
[in] self
[in] ownAvg
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 336 of file ReversiAnz.py.
setOwnEdgeCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnEdgeCnt (self, ownEdgeCnt)
セッター
Parameters
[in] self
[in] ownEdgeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 386 of file ReversiAnz.py.
setOwnEdgeSideOneCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnEdgeSideOneCnt (self, ownEdgeSideOneCnt)
セッター
Parameters
[in] self
[in] ownEdgeSideOneCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 411 of file ReversiAnz.py.
setOwnEdgeSideOtherCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnEdgeSideOtherCnt (self, ownEdgeSideOtherCnt)
セッター
Parameters
[in] self
[in] ownEdgeSideOtherCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 486 of file ReversiAnz.py.
setOwnEdgeSideThreeCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnEdgeSideThreeCnt (self, ownEdgeSideThreeCnt)
セッター
Parameters
[in] self
[in] ownEdgeSideThreeCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 461 of file ReversiAnz.py.
setOwnEdgeSideTwoCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnEdgeSideTwoCnt (self, ownEdgeSideTwoCnt)
セッター
Parameters
[in] self
[in] ownEdgeSideTwoCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 436 of file ReversiAnz.py.
setOwnMax()
def reversi.model.ReversiAnz.ReversiAnz.setOwnMax (self, ownMax)
セッター
Parameters
[in] self
[in] ownMax
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 311 of file ReversiAnz.py.
setOwnMin()
def reversi.model.ReversiAnz.ReversiAnz.setOwnMin (self, ownMin)
セッター
Parameters
[in] self
[in] ownMin
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 286 of file ReversiAnz.py.
setOwnPointCnt()
def reversi.model.ReversiAnz.ReversiAnz.setOwnPointCnt (self, ownPointCnt)
セッター
Parameters
[in] self
[in] ownPointCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 361 of file ReversiAnz.py.
setPointCnt()
def reversi.model.ReversiAnz.ReversiAnz.setPointCnt (self, pointCnt)
セッター
Parameters
[in] self
[in] pointCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.06
Definition at line 136 of file ReversiAnz.py.
The documentation for this class was generated from the following file:
model/ReversiAnz.py