ReversiPython: reversi.model.ReversiPlay.ReversiPlay Class Reference
reversi.model.ReversiPlay.ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
def __init__ (self)
コンストラクタ
def getmReversi (self)
ゲッター
def setmReversi (self, mReversi)
セッター
def getmSetting (self)
ゲッター
def setmSetting (self, mSetting)
セッター
def getmCurColor (self)
ゲッター
def setmCurColor (self, mCurColor)
セッター
def getmCpu (self)
ゲッター
def setmCpu (self, mCpu)
セッター
def getmEdge (self)
ゲッター
def setmEdge (self, mEdge)
セッター
def getmPassEnaB (self)
ゲッター
def setmPassEnaB (self, mPassEnaB)
セッター
def getmPassEnaW (self)
ゲッター
def setmPassEnaW (self, mPassEnaW)
セッター
def getmGameEndSts (self)
ゲッター
def setmGameEndSts (self, mGameEndSts)
セッター
def getmPlayLock (self)
ゲッター
def setmPlayLock (self, mPlayLock)
セッター
def getmDelegate (self)
ゲッター
def setmDelegate (self, mDelegate)
セッター
def reversiPlay (self, y, x)
リバーシプレイ
def reversiPlaySub (self, cpuEna, tmpCol)
リバーシプレイサブ
def reversiPlayEnd (self)
リバーシプレイ終了
def reversiPlayPass (self, color)
リバーシプレイパス
def reversiPlayCpu (self, color, cpuEna)
リバーシプレイコンピューター
def drawUpdate (self, assist)
マス描画更新
def drawUpdateForcibly (self, assist)
マス描画強制更新
def reset (self)
リセット処理
def gameEndAnimExec (self)
ゲーム終了アニメーション
def sendDrawMsg (self, y, x)
描画メッセージ送信
def sendDrawInfoMsg (self, y, x)
情報描画メッセージ送信
def execMessage (self, what, obj)
メッセージ
def ViewMsgDlgLocal (self, title, msg)
メッセージダイアログ
def DrawSingleLocal (self, y, x, sts, bk, text)
1マス描画
def CurColMsgLocal (self, text)
現在の色メッセージ
def CurStsMsgLocal (self, text)
現在のステータスメッセージ
def WaitLocal (self, time)
ウェイト
Properties
mReversi = property(getmReversi, setmReversi)
mSetting = property(getmSetting, setmSetting)
mCurColor = property(getmCurColor, setmCurColor)
mCpu = property(getmCpu, setmCpu)
mEdge = property(getmEdge, setmEdge)
mPassEnaB = property(getmPassEnaB, setmPassEnaB)
mPassEnaW = property(getmPassEnaW, setmPassEnaW)
mGameEndSts = property(getmGameEndSts, setmGameEndSts)
mPlayLock = property(getmPlayLock, setmPlayLock)
mDelegate = property(getmDelegate, setmDelegate)
Private Attributes
__mReversi
__mSetting
__mCpu
__mEdge
__mCurColor
__mPassEnaB
__mPassEnaW
__mGameEndSts
__mPlayLock
__mDelegate
Detailed Description
リバーシプレイクラス
Definition at line 29 of file ReversiPlay.py.
Constructor & Destructor Documentation
__init__()
def reversi.model.ReversiPlay.ReversiPlay.__init__ (self)
コンストラクタ
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 40 of file ReversiPlay.py.
Member Function Documentation
CurColMsgLocal()
def reversi.model.ReversiPlay.ReversiPlay.CurColMsgLocal (self, text)
現在の色メッセージ
Parameters
[in] self
[in] text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 1036 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.execMessage().
CurStsMsgLocal()
def reversi.model.ReversiPlay.ReversiPlay.CurStsMsgLocal (self, text)
現在のステータスメッセージ
Parameters
[in] self
[in] text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 1050 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.execMessage().
DrawSingleLocal()
def reversi.model.ReversiPlay.ReversiPlay.DrawSingleLocal (self, y, x, sts, bk, text)
1マス描画
Parameters
[in] self
[in] y Y座標
[in] x X座標
[in] sts ステータス
[in] bk 背景
[in] text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 1022 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.execMessage().
drawUpdate()
def reversi.model.ReversiPlay.ReversiPlay.drawUpdate (self, assist)
マス描画更新
Parameters
[in] self
[in] assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 719 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlayCpu().
drawUpdateForcibly()
def reversi.model.ReversiPlay.ReversiPlay.drawUpdateForcibly (self, assist)
マス描画強制更新
Parameters
[in] self
[in] assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 747 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reset().
execMessage()
def reversi.model.ReversiPlay.ReversiPlay.execMessage (self, what, obj)
メッセージ
Parameters
[in] self
[in] what
[in] obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 914 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.drawUpdate(), reversi.model.ReversiPlay.ReversiPlay.drawUpdateForcibly(), reversi.model.ReversiPlay.ReversiPlay.gameEndAnimExec(), reversi.model.ReversiPlay.ReversiPlay.reset(), reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), reversi.model.ReversiPlay.ReversiPlay.reversiPlayCpu(), reversi.model.ReversiPlay.ReversiPlay.reversiPlayEnd(), reversi.model.ReversiPlay.ReversiPlay.sendDrawInfoMsg(), and reversi.model.ReversiPlay.ReversiPlay.sendDrawMsg().
gameEndAnimExec()
def reversi.model.ReversiPlay.ReversiPlay.gameEndAnimExec (self)
ゲーム終了アニメーション
Parameters
[in] self
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 815 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlayEnd().
getmCpu()
def reversi.model.ReversiPlay.ReversiPlay.getmCpu (self)
ゲッター
Parameters
[in] self
Returns
mCpu
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 140 of file ReversiPlay.py.
getmCurColor()
def reversi.model.ReversiPlay.ReversiPlay.getmCurColor (self)
ゲッター
Parameters
[in] self
Returns
mCurColor
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 115 of file ReversiPlay.py.
getmDelegate()
def reversi.model.ReversiPlay.ReversiPlay.getmDelegate (self)
ゲッター
Parameters
[in] self
Returns
mDelegate
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 290 of file ReversiPlay.py.
getmEdge()
def reversi.model.ReversiPlay.ReversiPlay.getmEdge (self)
ゲッター
Parameters
[in] self
Returns
mEdge
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 165 of file ReversiPlay.py.
getmGameEndSts()
def reversi.model.ReversiPlay.ReversiPlay.getmGameEndSts (self)
ゲッター
Parameters
[in] self
Returns
mGameEndSts
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 240 of file ReversiPlay.py.
getmPassEnaB()
def reversi.model.ReversiPlay.ReversiPlay.getmPassEnaB (self)
ゲッター
Parameters
[in] self
Returns
mPassEnaB
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 190 of file ReversiPlay.py.
getmPassEnaW()
def reversi.model.ReversiPlay.ReversiPlay.getmPassEnaW (self)
ゲッター
Parameters
[in] self
Returns
mPassEnaW
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 215 of file ReversiPlay.py.
getmPlayLock()
def reversi.model.ReversiPlay.ReversiPlay.getmPlayLock (self)
ゲッター
Parameters
[in] self
Returns
mPlayLock
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 265 of file ReversiPlay.py.
getmReversi()
def reversi.model.ReversiPlay.ReversiPlay.getmReversi (self)
ゲッター
Parameters
[in] self
Returns
mReversi
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 65 of file ReversiPlay.py.
getmSetting()
def reversi.model.ReversiPlay.ReversiPlay.getmSetting (self)
ゲッター
Parameters
[in] self
Returns
mSetting
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 90 of file ReversiPlay.py.
reset()
def reversi.model.ReversiPlay.ReversiPlay.reset (self)
リセット処理
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 770 of file ReversiPlay.py.
Referenced by reversi.model.ReversiSetting.ReversiSetting.__init__().
reversiPlay()
def reversi.model.ReversiPlay.ReversiPlay.reversiPlay (self, y, x)
リバーシプレイ
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 317 of file ReversiPlay.py.
reversiPlayCpu()
def reversi.model.ReversiPlay.ReversiPlay.reversiPlayCpu (self, color, cpuEna)
リバーシプレイコンピューター
Parameters
[in] self
[in] color CPU色
[in] cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 510 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlaySub().
reversiPlayEnd()
def reversi.model.ReversiPlay.ReversiPlay.reversiPlayEnd (self)
リバーシプレイ終了
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 431 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlaySub().
reversiPlayPass()
def reversi.model.ReversiPlay.ReversiPlay.reversiPlayPass (self, color)
リバーシプレイパス
Parameters
[in] self
[in] color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 486 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlaySub().
reversiPlaySub()
def reversi.model.ReversiPlay.ReversiPlay.reversiPlaySub (self, cpuEna, tmpCol)
リバーシプレイサブ
Parameters
[in] self
[in] cpuEna
[in] tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 405 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlay().
sendDrawInfoMsg()
def reversi.model.ReversiPlay.ReversiPlay.sendDrawInfoMsg (self, y, x)
情報描画メッセージ送信
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 896 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.drawUpdate().
sendDrawMsg()
def reversi.model.ReversiPlay.ReversiPlay.sendDrawMsg (self, y, x)
描画メッセージ送信
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 878 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.drawUpdate(), reversi.model.ReversiPlay.ReversiPlay.gameEndAnimExec(), reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlayCpu().
setmCpu()
def reversi.model.ReversiPlay.ReversiPlay.setmCpu (self, mCpu)
セッター
Parameters
[in] self
[in] mCpu
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 153 of file ReversiPlay.py.
setmCurColor()
def reversi.model.ReversiPlay.ReversiPlay.setmCurColor (self, mCurColor)
セッター
Parameters
[in] self
[in] mCurColor
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 128 of file ReversiPlay.py.
setmDelegate()
def reversi.model.ReversiPlay.ReversiPlay.setmDelegate (self, mDelegate)
セッター
Parameters
[in] self
[in] mDelegate
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 303 of file ReversiPlay.py.
setmEdge()
def reversi.model.ReversiPlay.ReversiPlay.setmEdge (self, mEdge)
セッター
Parameters
[in] self
[in] mEdge
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 178 of file ReversiPlay.py.
setmGameEndSts()
def reversi.model.ReversiPlay.ReversiPlay.setmGameEndSts (self, mGameEndSts)
セッター
Parameters
[in] self
[in] mGameEndSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 253 of file ReversiPlay.py.
setmPassEnaB()
def reversi.model.ReversiPlay.ReversiPlay.setmPassEnaB (self, mPassEnaB)
セッター
Parameters
[in] self
[in] mPassEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 203 of file ReversiPlay.py.
setmPassEnaW()
def reversi.model.ReversiPlay.ReversiPlay.setmPassEnaW (self, mPassEnaW)
セッター
Parameters
[in] self
[in] mPassEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 228 of file ReversiPlay.py.
setmPlayLock()
def reversi.model.ReversiPlay.ReversiPlay.setmPlayLock (self, mPlayLock)
セッター
Parameters
[in] self
[in] mPlayLock
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 278 of file ReversiPlay.py.
setmReversi()
def reversi.model.ReversiPlay.ReversiPlay.setmReversi (self, mReversi)
セッター
Parameters
[in] self
[in] mReversi
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 78 of file ReversiPlay.py.
setmSetting()
def reversi.model.ReversiPlay.ReversiPlay.setmSetting (self, mSetting)
セッター
Parameters
[in] self
[in] mSetting
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 103 of file ReversiPlay.py.
ViewMsgDlgLocal()
def reversi.model.ReversiPlay.ReversiPlay.ViewMsgDlgLocal (self, title, msg)
メッセージダイアログ
Parameters
[in] self
[in] title タイトル
[in] msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 1004 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), reversi.model.ReversiPlay.ReversiPlay.reversiPlayEnd(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlayPass().
WaitLocal()
def reversi.model.ReversiPlay.ReversiPlay.WaitLocal (self, time)
ウェイト
Parameters
[in] self
[in] time ウェイト時間(msec)
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.13
Definition at line 1064 of file ReversiPlay.py.
Referenced by reversi.model.ReversiPlay.ReversiPlay.drawUpdate(), reversi.model.ReversiPlay.ReversiPlay.gameEndAnimExec(), reversi.model.ReversiPlay.ReversiPlay.reversiPlay(), and reversi.model.ReversiPlay.ReversiPlay.reversiPlayEnd().
The documentation for this class was generated from the following file:
model/ReversiPlay.py