ReversiPython: reversi.model.Reversi.Reversi Class Reference
reversi.model.Reversi.Reversi Class Reference
リバーシクラス
Public Member Functions
def __init__ (self, masuCnt, masuMax)
コンストラクタ
def getmMasuSts (self)
ゲッター
def setmMasuSts (self, mMasuSts)
セッター
def getmMasuStsOld (self)
ゲッター
def setmMasuStsOld (self, mMasuStsOld)
セッター
def getmMasuStsEnaB (self)
ゲッター
def setmMasuStsEnaB (self, mMasuStsEnaB)
セッター
def getmMasuStsCntB (self)
ゲッター
def setmMasuStsCntB (self, mMasuStsCntB)
セッター
def getmMasuStsPassB (self)
ゲッター
def setmMasuStsPassB (self, mMasuStsPassB)
セッター
def getmMasuStsAnzB (self)
ゲッター
def setmMasuStsAnzB (self, mMasuStsAnzB)
セッター
def getmMasuPointB (self)
ゲッター
def setmMasuPointB (self, mMasuPointB)
セッター
def getmMasuPointCntB (self)
ゲッター
def setmMasuPointCntB (self, mMasuPointCntB)
セッター
def getmMasuBetCntB (self)
ゲッター
def setmMasuBetCntB (self, mMasuBetCntB)
セッター
def getmMasuStsEnaW (self)
ゲッター
def setmMasuStsEnaW (self, mMasuStsEnaW)
セッター
def getmMasuStsCntW (self)
ゲッター
def setmMasuStsCntW (self, mMasuStsCntW)
セッター
def getmMasuStsPassW (self)
ゲッター
def setmMasuStsPassW (self, mMasuStsPassW)
セッター
def getmMasuStsAnzW (self)
ゲッター
def setmMasuStsAnzW (self, mMasuStsAnzW)
セッター
def getmMasuPointW (self)
ゲッター
def setmMasuPointW (self, mMasuPointW)
セッター
def getmMasuPointCntW (self)
ゲッター
def setmMasuPointCntW (self, mMasuPointCntW)
セッター
def getmMasuBetCntW (self)
ゲッター
def setmMasuBetCntW (self, mMasuBetCntW)
セッター
def getmMasuCnt (self)
ゲッター
def setmMasuCnt (self, mMasuCnt)
セッター
def getmMasuCntMax (self)
ゲッター
def setmMasuCntMax (self, mMasuCntMax)
セッター
def getmMasuHist (self)
ゲッター
def setmMasuHist (self, mMasuHist)
セッター
def getmMasuHistCur (self)
ゲッター
def setmMasuHistCur (self, mMasuHistCur)
セッター
def reset (self)
リセット
def makeMasuSts (self, color)
各コマの置ける場所等のステータス作成
def revMasuSts (self, color, y, x)
コマをひっくり返す
def checkPara (self, para, min, max)
パラメーター範囲チェック
def AnalysisReversiBlack (self)
解析を行う(黒)
def AnalysisReversiWhite (self)
解析を行う(白)
def AnalysisReversi (self, bPassEna, wPassEna)
解析を行う
def getMasuSts (self, y, x)
マスステータスを取得
def getMasuStsOld (self, y, x)
以前のマスステータスを取得
def getMasuStsEna (self, color, y, x)
指定座標に指定色を置けるかチェック
def getMasuStsCnt (self, color, y, x)
指定座標の獲得コマ数取得
def getColorEna (self, color)
指定色が現在置ける場所があるかチェック
def getGameEndSts (self)
ゲーム終了かチェック
def setMasuSts (self, color, y, x)
指定座標にコマを置く
def setMasuStsForcibly (self, color, y, x)
指定座標にコマを強制的に置く
def setMasuCnt (self, cnt)
マスの数変更
def getPoint (self, color, num)
ポイント座標取得
def getPointCnt (self, color)
ポイント座標数取得
def getBetCnt (self, color)
コマ数取得
def getPassEna (self, color, y, x)
パス判定
def getHistory (self, num)
履歴取得
def getHistoryCnt (self)
履歴数取得
def getPointAnz (self, color, y, x)
ポイント座標解析取得
def checkEdge (self, color, y, x)
角の隣に置いても角を取られないマス検索
def getEdgeSideZero (self, y, x)
指定座標が角か取得
def getEdgeSideOne (self, y, x)
指定座標が角の一つ手前か取得
def getEdgeSideTwo (self, y, x)
指定座標が角の二つ手前か取得
def getEdgeSideThree (self, y, x)
指定座標が角の三つ以上手前か取得
Properties
mMasuSts = property(getmMasuSts,setmMasuSts)
mMasuStsOld = property(getmMasuStsOld,setmMasuStsOld)
mMasuStsEnaB = property(getmMasuStsEnaB,setmMasuStsEnaB)
mMasuStsCntB = property(getmMasuStsCntB,setmMasuStsCntB)
mMasuStsPassB = property(getmMasuStsPassB,setmMasuStsPassB)
mMasuStsAnzB = property(getmMasuStsAnzB,setmMasuStsAnzB)
mMasuPointB = property(getmMasuPointB,setmMasuPointB)
mMasuPointCntB = property(getmMasuPointCntB,setmMasuPointCntB)
mMasuBetCntB = property(getmMasuBetCntB,setmMasuBetCntB)
mMasuStsEnaW = property(getmMasuStsEnaW,setmMasuStsEnaW)
mMasuStsCntW = property(getmMasuStsCntW,setmMasuStsCntW)
mMasuStsPassW = property(getmMasuStsPassW,setmMasuStsPassW)
mMasuStsAnzW = property(getmMasuStsAnzW,setmMasuStsAnzW)
mMasuPointW = property(getmMasuPointW,setmMasuPointW)
mMasuPointCntW = property(getmMasuPointCntW,setmMasuPointCntW)
mMasuBetCntW = property(getmMasuBetCntW,setmMasuBetCntW)
mMasuCnt = property(getmMasuCnt,setmMasuCnt)
mMasuCntMax = property(getmMasuCntMax,setmMasuCntMax)
mMasuHist = property(getmMasuHist,setmMasuHist)
mMasuHistCur = property(getmMasuHistCur,setmMasuHistCur)
Private Attributes
__mMasuCnt
__mMasuCntMax
__mMasuSts
__mMasuStsOld
__mMasuStsEnaB
__mMasuStsCntB
__mMasuStsPassB
__mMasuStsAnzB
__mMasuPointB
__mMasuPointCntB
__mMasuStsEnaW
__mMasuStsCntW
__mMasuStsPassW
__mMasuStsAnzW
__mMasuPointW
__mMasuPointCntW
__mMasuBetCntB
__mMasuBetCntW
__mMasuHist
__mMasuHistCur
Detailed Description
リバーシクラス
Definition at line 31 of file Reversi.py.
Constructor & Destructor Documentation
__init__()
def reversi.model.Reversi.Reversi.__init__ (self, masuCnt, masuMax)
コンストラクタ
Parameters
[in] self
[in] masuCnt 縦横マス数
[in] masuMax 縦横マス最大数
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 44 of file Reversi.py.
Member Function Documentation
AnalysisReversi()
def reversi.model.Reversi.Reversi.AnalysisReversi (self, bPassEna, wPassEna)
解析を行う
Parameters
[in] self
[in] bPassEna 1=黒パス有効
[in] wPassEna 1=白パス有効
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1325 of file Reversi.py.
AnalysisReversiBlack()
def reversi.model.Reversi.Reversi.AnalysisReversiBlack (self)
解析を行う(黒)
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1031 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversi().
AnalysisReversiWhite()
def reversi.model.Reversi.Reversi.AnalysisReversiWhite (self)
解析を行う(白)
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1178 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversi().
checkEdge()
def reversi.model.Reversi.Reversi.checkEdge (self, color, y, x)
角の隣に置いても角を取られないマス検索
Parameters
[in] self
[in] color 色
[in] y Y座標
[in] x X座標
Returns
0 : 取られる それ以外 : 取られない
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1677 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
checkPara()
def reversi.model.Reversi.Reversi.checkPara (self, para, min, max)
パラメーター範囲チェック
Parameters
[in] self
[in] para チェックパラメーター
[in] min パラメーター最小値
[in] max パラメーター最大値
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1016 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.getHistory(), reversi.model.Reversi.Reversi.getMasuSts(), reversi.model.Reversi.Reversi.getMasuStsCnt(), reversi.model.Reversi.Reversi.getMasuStsEna(), reversi.model.Reversi.Reversi.getMasuStsOld(), reversi.model.Reversi.Reversi.getPassEna(), reversi.model.Reversi.Reversi.getPoint(), reversi.model.Reversi.Reversi.getPointAnz(), and reversi.model.Reversi.Reversi.setMasuCnt().
getBetCnt()
def reversi.model.Reversi.Reversi.getBetCnt (self, color)
コマ数取得
Parameters
[in] self
[in] color コマ色
Returns
コマ数取得
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1583 of file Reversi.py.
getColorEna()
def reversi.model.Reversi.Reversi.getColorEna (self, color)
指定色が現在置ける場所があるかチェック
Parameters
[in] self
[in] color コマ色
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1436 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), reversi.model.Reversi.Reversi.AnalysisReversiWhite(), and reversi.model.Reversi.Reversi.getGameEndSts().
getEdgeSideOne()
def reversi.model.Reversi.Reversi.getEdgeSideOne (self, y, x)
指定座標が角の一つ手前か取得
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1913 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
getEdgeSideThree()
def reversi.model.Reversi.Reversi.getEdgeSideThree (self, y, x)
指定座標が角の三つ以上手前か取得
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1967 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
getEdgeSideTwo()
def reversi.model.Reversi.Reversi.getEdgeSideTwo (self, y, x)
指定座標が角の二つ手前か取得
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1940 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
getEdgeSideZero()
def reversi.model.Reversi.Reversi.getEdgeSideZero (self, y, x)
指定座標が角か取得
Parameters
[in] self
[in] y Y座標
[in] x X座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1894 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
getGameEndSts()
def reversi.model.Reversi.Reversi.getGameEndSts (self)
ゲーム終了かチェック
Parameters
[in] self
Returns
0 : 続行 それ以外 : ゲーム終了
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1454 of file Reversi.py.
getHistory()
def reversi.model.Reversi.Reversi.getHistory (self, num)
履歴取得
Parameters
[in] self
[in] num ポイント
Returns
履歴 null : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1625 of file Reversi.py.
getHistoryCnt()
def reversi.model.Reversi.Reversi.getHistoryCnt (self)
履歴数取得
Parameters
[in] self
Returns
履歴数
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1640 of file Reversi.py.
getMasuSts()
def reversi.model.Reversi.Reversi.getMasuSts (self, y, x)
マスステータスを取得
Parameters
[in] self
[in] y 取得するマスのY座標
[in] x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1361 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.checkEdge().
getMasuStsCnt()
def reversi.model.Reversi.Reversi.getMasuStsCnt (self, color, y, x)
指定座標の獲得コマ数取得
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
-1 : 失敗 それ以外 : 獲得コマ数
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1417 of file Reversi.py.
getMasuStsEna()
def reversi.model.Reversi.Reversi.getMasuStsEna (self, color, y, x)
指定座標に指定色を置けるかチェック
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
1 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1396 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), reversi.model.Reversi.Reversi.AnalysisReversiWhite(), reversi.model.Reversi.Reversi.getColorEna(), and reversi.model.Reversi.Reversi.setMasuSts().
getMasuStsOld()
def reversi.model.Reversi.Reversi.getMasuStsOld (self, y, x)
以前のマスステータスを取得
Parameters
[in] self
[in] y 取得するマスのY座標
[in] x 取得するマスのX座標
Returns
-1 : 失敗 それ以外 : マスステータス
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1378 of file Reversi.py.
getmMasuBetCntB()
def reversi.model.Reversi.Reversi.getmMasuBetCntB (self)
ゲッター
Parameters
[in] self
Returns
mMasuBetCntB
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 310 of file Reversi.py.
getmMasuBetCntW()
def reversi.model.Reversi.Reversi.getmMasuBetCntW (self)
ゲッター
Parameters
[in] self
Returns
mMasuBetCntW
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 485 of file Reversi.py.
getmMasuCnt()
def reversi.model.Reversi.Reversi.getmMasuCnt (self)
ゲッター
Parameters
[in] self
Returns
mMasuCnt
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 510 of file Reversi.py.
getmMasuCntMax()
def reversi.model.Reversi.Reversi.getmMasuCntMax (self)
ゲッター
Parameters
[in] self
Returns
mMasuCntMax
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 535 of file Reversi.py.
getmMasuHist()
def reversi.model.Reversi.Reversi.getmMasuHist (self)
ゲッター
Parameters
[in] self
Returns
mMasuHist[]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 560 of file Reversi.py.
getmMasuHistCur()
def reversi.model.Reversi.Reversi.getmMasuHistCur (self)
ゲッター
Parameters
[in] self
Returns
mMasuHistCur
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 585 of file Reversi.py.
getmMasuPointB()
def reversi.model.Reversi.Reversi.getmMasuPointB (self)
ゲッター
Parameters
[in] self
Returns
mMasuPointB[]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 260 of file Reversi.py.
getmMasuPointCntB()
def reversi.model.Reversi.Reversi.getmMasuPointCntB (self)
ゲッター
Parameters
[in] self
Returns
mMasuPointCntB
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 285 of file Reversi.py.
getmMasuPointCntW()
def reversi.model.Reversi.Reversi.getmMasuPointCntW (self)
ゲッター
Parameters
[in] self
Returns
mMasuPointCntW
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 460 of file Reversi.py.
getmMasuPointW()
def reversi.model.Reversi.Reversi.getmMasuPointW (self)
ゲッター
Parameters
[in] self
Returns
mMasuPointW[]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 435 of file Reversi.py.
getmMasuSts()
def reversi.model.Reversi.Reversi.getmMasuSts (self)
ゲッター
Parameters
[in] self
Returns
mMasuSts[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 110 of file Reversi.py.
getmMasuStsAnzB()
def reversi.model.Reversi.Reversi.getmMasuStsAnzB (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsAnzB[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 235 of file Reversi.py.
getmMasuStsAnzW()
def reversi.model.Reversi.Reversi.getmMasuStsAnzW (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsAnzW[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 410 of file Reversi.py.
getmMasuStsCntB()
def reversi.model.Reversi.Reversi.getmMasuStsCntB (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsCntB[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 185 of file Reversi.py.
getmMasuStsCntW()
def reversi.model.Reversi.Reversi.getmMasuStsCntW (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsCntW[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 360 of file Reversi.py.
getmMasuStsEnaB()
def reversi.model.Reversi.Reversi.getmMasuStsEnaB (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsEnaB[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 160 of file Reversi.py.
getmMasuStsEnaW()
def reversi.model.Reversi.Reversi.getmMasuStsEnaW (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsEnaW[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 335 of file Reversi.py.
getmMasuStsOld()
def reversi.model.Reversi.Reversi.getmMasuStsOld (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsOld[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 135 of file Reversi.py.
getmMasuStsPassB()
def reversi.model.Reversi.Reversi.getmMasuStsPassB (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsPassB[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 210 of file Reversi.py.
getmMasuStsPassW()
def reversi.model.Reversi.Reversi.getmMasuStsPassW (self)
ゲッター
Parameters
[in] self
Returns
mMasuStsPassW[][]
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 385 of file Reversi.py.
getPassEna()
def reversi.model.Reversi.Reversi.getPassEna (self, color, y, x)
パス判定
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
パス判定
0 : NOT PASS
1 : PASS
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1606 of file Reversi.py.
getPoint()
def reversi.model.Reversi.Reversi.getPoint (self, color, num)
ポイント座標取得
Parameters
[in] self
[in] color コマ色
[in] num ポイント
Returns
ポイント座標 null : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1546 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.setMasuSts().
getPointAnz()
def reversi.model.Reversi.Reversi.getPointAnz (self, color, y, x)
ポイント座標解析取得
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
ポイント座標解析 null : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1656 of file Reversi.py.
getPointCnt()
def reversi.model.Reversi.Reversi.getPointCnt (self, color)
ポイント座標数取得
Parameters
[in] self
[in] color コマ色
Returns
ポイント座標数取得
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1565 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), and reversi.model.Reversi.Reversi.AnalysisReversiWhite().
makeMasuSts()
def reversi.model.Reversi.Reversi.makeMasuSts (self, color)
各コマの置ける場所等のステータス作成
Parameters
[in] self
[in] color ステータスを作成するコマ
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 639 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversi(), reversi.model.Reversi.Reversi.AnalysisReversiBlack(), reversi.model.Reversi.Reversi.AnalysisReversiWhite(), reversi.model.Reversi.Reversi.reset(), and reversi.model.Reversi.Reversi.setMasuSts().
reset()
def reversi.model.Reversi.Reversi.reset (self)
リセット
Parameters
[in] self
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 610 of file Reversi.py.
Referenced by reversi.model.ReversiAnz.ReversiAnz.__init__(), reversi.model.ReversiHistory.ReversiHistory.__init__(), reversi.model.ReversiSetting.ReversiSetting.__init__(), reversi.model.Reversi.Reversi.__init__(), reversi.model.Reversi.Reversi.AnalysisReversi(), and reversi.model.Reversi.Reversi.setMasuCnt().
revMasuSts()
def reversi.model.Reversi.Reversi.revMasuSts (self, color, y, x)
コマをひっくり返す
Parameters
[in] self
[in] color ひっくり返す元コマ
[in] y ひっくり返す元コマのY座標
[in] x ひっくり返す元コマのX座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 817 of file Reversi.py.
Referenced by reversi.model.Reversi.Reversi.AnalysisReversiBlack(), reversi.model.Reversi.Reversi.AnalysisReversiWhite(), and reversi.model.Reversi.Reversi.setMasuSts().
setMasuCnt()
def reversi.model.Reversi.Reversi.setMasuCnt (self, cnt)
マスの数変更
Parameters
[in] self
[in] cnt マスの数
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1523 of file Reversi.py.
setMasuSts()
def reversi.model.Reversi.Reversi.setMasuSts (self, color, y, x)
指定座標にコマを置く
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1474 of file Reversi.py.
setMasuStsForcibly()
def reversi.model.Reversi.Reversi.setMasuStsForcibly (self, color, y, x)
指定座標にコマを強制的に置く
Parameters
[in] self
[in] color コマ色
[in] y マスのY座標
[in] x マスのX座標
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 1506 of file Reversi.py.
setmMasuBetCntB()
def reversi.model.Reversi.Reversi.setmMasuBetCntB (self, mMasuBetCntB)
セッター
Parameters
[in] self
[in] mMasuBetCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 323 of file Reversi.py.
setmMasuBetCntW()
def reversi.model.Reversi.Reversi.setmMasuBetCntW (self, mMasuBetCntW)
セッター
Parameters
[in] self
[in] mMasuBetCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 498 of file Reversi.py.
setmMasuCnt()
def reversi.model.Reversi.Reversi.setmMasuCnt (self, mMasuCnt)
セッター
Parameters
[in] self
[in] mMasuCnt
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 523 of file Reversi.py.
setmMasuCntMax()
def reversi.model.Reversi.Reversi.setmMasuCntMax (self, mMasuCntMax)
セッター
Parameters
[in] self
[in] mMasuCntMax
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 548 of file Reversi.py.
setmMasuHist()
def reversi.model.Reversi.Reversi.setmMasuHist (self, mMasuHist)
セッター
Parameters
[in] self
[in] mMasuHist
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 573 of file Reversi.py.
setmMasuHistCur()
def reversi.model.Reversi.Reversi.setmMasuHistCur (self, mMasuHistCur)
セッター
Parameters
[in] self
[in] mMasuHistCur
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 598 of file Reversi.py.
setmMasuPointB()
def reversi.model.Reversi.Reversi.setmMasuPointB (self, mMasuPointB)
セッター
Parameters
[in] self
[in] mMasuPointB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 273 of file Reversi.py.
setmMasuPointCntB()
def reversi.model.Reversi.Reversi.setmMasuPointCntB (self, mMasuPointCntB)
セッター
Parameters
[in] self
[in] mMasuPointCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 298 of file Reversi.py.
setmMasuPointCntW()
def reversi.model.Reversi.Reversi.setmMasuPointCntW (self, mMasuPointCntW)
セッター
Parameters
[in] self
[in] mMasuPointCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 473 of file Reversi.py.
setmMasuPointW()
def reversi.model.Reversi.Reversi.setmMasuPointW (self, mMasuPointW)
セッター
Parameters
[in] self
[in] mMasuPointW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 448 of file Reversi.py.
setmMasuSts()
def reversi.model.Reversi.Reversi.setmMasuSts (self, mMasuSts)
セッター
Parameters
[in] self
[in] mMasuSts
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 123 of file Reversi.py.
setmMasuStsAnzB()
def reversi.model.Reversi.Reversi.setmMasuStsAnzB (self, mMasuStsAnzB)
セッター
Parameters
[in] self
[in] mMasuStsAnzB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 248 of file Reversi.py.
setmMasuStsAnzW()
def reversi.model.Reversi.Reversi.setmMasuStsAnzW (self, mMasuStsAnzW)
セッター
Parameters
[in] self
[in] mMasuStsAnzW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 423 of file Reversi.py.
setmMasuStsCntB()
def reversi.model.Reversi.Reversi.setmMasuStsCntB (self, mMasuStsCntB)
セッター
Parameters
[in] self
[in] mMasuStsCntB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 198 of file Reversi.py.
setmMasuStsCntW()
def reversi.model.Reversi.Reversi.setmMasuStsCntW (self, mMasuStsCntW)
セッター
Parameters
[in] self
[in] mMasuStsCntW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 373 of file Reversi.py.
setmMasuStsEnaB()
def reversi.model.Reversi.Reversi.setmMasuStsEnaB (self, mMasuStsEnaB)
セッター
Parameters
[in] self
[in] mMasuStsEnaB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 173 of file Reversi.py.
setmMasuStsEnaW()
def reversi.model.Reversi.Reversi.setmMasuStsEnaW (self, mMasuStsEnaW)
セッター
Parameters
[in] self
[in] mMasuStsEnaW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 348 of file Reversi.py.
setmMasuStsOld()
def reversi.model.Reversi.Reversi.setmMasuStsOld (self, mMasuStsOld)
セッター
Parameters
[in] self
[in] mMasuStsOld
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 148 of file Reversi.py.
setmMasuStsPassB()
def reversi.model.Reversi.Reversi.setmMasuStsPassB (self, mMasuStsPassB)
セッター
Parameters
[in] self
[in] mMasuStsPassB
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 223 of file Reversi.py.
setmMasuStsPassW()
def reversi.model.Reversi.Reversi.setmMasuStsPassW (self, mMasuStsPassW)
セッター
Parameters
[in] self
[in] mMasuStsPassW
Returns
ありません
Author
Yuta Yoshinaga
Date
2018.11.11
Definition at line 398 of file Reversi.py.
The documentation for this class was generated from the following file:
model/Reversi.py